language: python
python:
  - "3.7"
# command to install dependencies
install:
  - sudo pip3 install tox-travis
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install requests
# command to run tests
script:
  - tox

