language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip3 install tox-travis
  - pip3 install -r requirements.txt
  - pip3 install requests
# command to run tests
before_script:
  - export FLASK_DEBUG=1
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
script:
  - python -m unittest discover
