language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip3 install requests
# command to run tests
script:
  - flask run &
  - tox

